<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-17T18:07:30 IST" name="Default suite" finished-at="2025-06-17T18:07:49 IST" duration-ms="19251">
    <groups>
    </groups>
    <test started-at="2025-06-17T18:07:30 IST" name="Default test" finished-at="2025-06-17T18:07:49 IST" duration-ms="19251">
      <class name="com.comcast.crm.Debugging.CreateOrgTest">
        <test-method is-config="true" signature="configBS()[pri:0, instance:com.comcast.crm.Debugging.CreateOrgTest@229f66ed]" started-at="2025-06-17T18:07:29 IST" name="configBS" finished-at="2025-06-17T18:07:30 IST" duration-ms="621" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBS -->
        <test-method is-config="true" signature="configBC()[pri:0, instance:com.comcast.crm.Debugging.CreateOrgTest@229f66ed]" started-at="2025-06-17T18:07:30 IST" name="configBC" finished-at="2025-06-17T18:07:33 IST" duration-ms="2657" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBC -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.comcast.crm.Debugging.CreateOrgTest@229f66ed]" started-at="2025-06-17T18:07:33 IST" name="configBM" finished-at="2025-06-17T18:07:36 IST" duration-ms="3901" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method signature="createOrganizationTest()[pri:0, instance:com.comcast.crm.Debugging.CreateOrgTest@229f66ed]" started-at="2025-06-17T18:07:36 IST" name="createOrganizationTest" finished-at="2025-06-17T18:07:47 IST" duration-ms="10761" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1066)
at org.testng.Assert.assertEquals(Assert.java:1030)
at org.testng.Assert.assertEquals(Assert.java:1076)
at com.comcast.crm.Debugging.CreateOrgTest.createOrganizationTest(CreateOrgTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrganizationTest -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.comcast.crm.Debugging.CreateOrgTest@229f66ed]" started-at="2025-06-17T18:07:48 IST" name="configAM" finished-at="2025-06-17T18:07:49 IST" duration-ms="1232" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configAC()[pri:0, instance:com.comcast.crm.Debugging.CreateOrgTest@229f66ed]" started-at="2025-06-17T18:07:49 IST" name="configAC" finished-at="2025-06-17T18:07:49 IST" duration-ms="339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC -->
        <test-method is-config="true" signature="configAS()[pri:0, instance:com.comcast.crm.Debugging.CreateOrgTest@229f66ed]" started-at="2025-06-17T18:07:49 IST" name="configAS" finished-at="2025-06-17T18:07:49 IST" duration-ms="21" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAS -->
      </class> <!-- com.comcast.crm.Debugging.CreateOrgTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
